### PR TITLE
Use rlibc

### PR DESCRIPTION
**Pull request by pepyakin**
cc @NikVolf

### CODE REVIEW

**Comment by NikVolf** [comment]
On the second thought, how about making it feature-gated?

**Comment by pepyakin** [comment]
What do you mean exactly?

**Comment by NikVolf** [comment]
I'd like to add feature so that if I compile with `pwasm-std/ext_memory` (whatever name), the older variant with `ext_memcpy`/`ext_memmov`/`ext_memset` externs is compiled

I think we need it pretty soon

**Comment by pepyakin** [comment]
> I think we need it pretty soon

Could you elaborate it a little more?

**Comment by NikVolf** [comment]
Optimization of contracts run via interpreter? I think using this kind of operations will be very slow with purely wasm instruction set

**Pull request merged**
