### PR TITLE
WIP: move to 1.29

### PR DESCRIPTION
**Pull request by Pzixel**
My attempt to move code to 1.29. Unfortunately, depended code like contracts or tutorials won't work on this version - some changes in macro system make current tutorials broken:

```
error[E0433]: failed to resolve. Use of undeclared type or module `Vec`
  --> src\lib.rs:66:5
   |
66 |     #[eth_abi(TokenEndpoint, TokenClient)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Use of undeclared type or module `Vec`

error[E0412]: cannot find type `Vec` in this scope
  --> src\lib.rs:66:5
   |
66 |     #[eth_abi(TokenEndpoint, TokenClient)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

### CODE REVIEW

**Comment by Pzixel** [comment]
Any reasons?

**Comment by NikVolf** [comment]
it's auto-closed because of your `fix paritytech/pwasm-std#76` in https://github.com/paritytech/pwasm-abi/pull/60, reopen if needed

**Comment by Pzixel** [comment]
That's weird, how `pwasm-abi` affects `pwasm-std` ;D

Going to fix it soon

**Comment by NikVolf** [comment]
Looks like a valid change for the latest nightly, why is this "WIP" ?

**Comment by Pzixel** [comment]
I needed to change toolchain version to match `pwasm-abi` (to make sure they have the same toolchain version) as well as check if depended code works fine with `pwasm-abi-derive`.

**Comment by fckt** [comment]
@Pzixel take a look https://github.com/paritytech/pwasm-abi/pull/64

**Comment by Pzixel** [comment]
Looks great! :)

**Pull request merged**
